version: '3'

services:
  backend_go:
    image: 'victorcuches28/proyecto_uno'
    container_name: "backend_go"
    volumes: 
      - type: bind
        source: /proc
        target: /proc
    pid: host
    restart: always
    ports:
      - "8080:8080"


  backend_py:
    image: 'victorcuches28/api_python'
    container_name: "backend_py"
    ports:
      - "6000:5000"

 