version: '3'

services:
  mysqldb:
    image: 'mysql'
    env_file: ./.env
    container_name: "database_container"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3307:3306  

  frontend:
    image: 'victorcuches28/proyecto_uno_frontend'
    container_name: "frontend_react"
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: 'victorcuches28/proyecto_uno_node'
    container_name: "backend_node"
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - "5000:5000"


volumes:
  mysql-data: